version: '2'
services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    image: enstar/enstar
    restart: always
    volumes:
    - ./:/server/http
    ports:
    - 8080:80
    networks:
    - enstar-net
    depends_on:
    - database
  database:
    image: mysql:8
    ports:
    - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
    - enstar-mysql:/var/lib/mysql
    networks:
    - enstar-net
networks:
  enstar-net:
    driver: "bridge"
volumes:
  enstar-mysql:
    driver: "local"